# Generated by Django 4.2.8 on 2023-12-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('district', models.CharField(max_length=255, verbose_name='Район военкомата')),
                ('confirm', models.BooleanField(default=False, verbose_name='Принять')),
                ('reject', models.BooleanField(default=False, verbose_name='Отклонить')),
                ('consideration', models.BooleanField(default=True, verbose_name='В рассмотрении')),
                ('cancel', models.BooleanField(default=False, verbose_name='Отменить')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embassy', models.CharField(max_length=255, verbose_name='Для посольства')),
                ('certificate_num', models.CharField(blank=True, max_length=255, verbose_name='Номер сертификата')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('executor_name', models.CharField(blank=True, max_length=255, verbose_name='Имя исполнителя')),
                ('project_authority_name', models.CharField(blank=True, max_length=255, verbose_name='Имя проектора')),
                ('project_authority_role', models.CharField(blank=True, max_length=255, verbose_name='Должность проектора')),
                ('confirm', models.BooleanField(default=False, verbose_name='Принять')),
                ('reject', models.BooleanField(default=False, verbose_name='Отклонить')),
                ('consideration', models.BooleanField(default=True, verbose_name='В рассмотрении')),
                ('cancel', models.BooleanField(default=False, verbose_name='Отменить')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_number', models.CharField(blank=True, max_length=255, verbose_name='Номер справки')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('certificate_num', models.CharField(blank=True, max_length=17, verbose_name='Номер сертификата')),
                ('confirm', models.BooleanField(default=False, verbose_name='Принять')),
                ('reject', models.BooleanField(default=False, verbose_name='Отклонить')),
                ('consideration', models.BooleanField(default=True, verbose_name='В рассмотрении')),
                ('cancel', models.BooleanField(default=False, verbose_name='Отменить')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_certificate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
