# Generated by Django 4.2.8 on 2023-12-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, verbose_name='ФИО')),
                ('login', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Логин')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('group_name', models.CharField(max_length=255, verbose_name='Группа')),
                ('study_degree', models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Магистр', 'Магистр')], max_length=8, verbose_name='Степень')),
                ('study_form', models.CharField(choices=[('Очное', 'Очное'), ('Заочное', 'Заочное'), ('Вечернее', 'Вечернее')], max_length=9, verbose_name='Обучение')),
                ('faculty_name', models.CharField(max_length=255, verbose_name='Факультет')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('course_num', models.PositiveSmallIntegerField(null=True, verbose_name='Курс')),
                ('period_start', models.DateField(null=True, verbose_name='Период обучения с')),
                ('period_end', models.DateField(null=True, verbose_name='Период обучения по')),
                ('normative_duration', models.PositiveSmallIntegerField(null=True, verbose_name='Нормативный срок освоения')),
                ('direction_name', models.CharField(max_length=255, verbose_name='Название бакалавриата')),
                ('university_name', models.CharField(max_length=255, verbose_name='Университет')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
